// Import createSlice from Redux Toolkit for creating a slice of the Redux store
import { createSlice } from "@reduxjs/toolkit";

// Define the type for the state
interface CounterState {
  value: number;
}

// Create a counter slice using createSlice
const counterSlice = createSlice({
  name: "counter", // Name of the slice, used as the key in the root reducer
  initialState: { value: 0 } as CounterState, // Initial state for this slice
  reducers: {
    // Define the increment reducer function, which increments the counter value
    increment: (state) => {
      state.value += 1;
    },
    // Define the decrement reducer function, which decrements the counter value
    decrement: (state) => {
      state.value -= 1;
    },
    // Define the doubled reducer function, which doubles the counter value
    doubled: (state) => {
      state.value *= 2;
    },
    // Define the half reducer function, which halves the counter value
    half: (state) => {
      state.value /= 2;
    },
    // Define the reset reducer function, which resets the counter value to 0
    reset: (state) => {
      state.value = 0;
    },
  },
});

// Export the increment and decrement action creators for dispatching the corresponding actions
export const { increment, decrement, doubled, reset, half } =
  counterSlice.actions;

// Export the reducer function generated by createSlice as the default export of this module
export default counterSlice.reducer;
