// Import createSlice and PayloadAction from Redux Toolkit for creating a slice of the Redux store
import { createSlice, PayloadAction } from "@reduxjs/toolkit";

// Define the shape of the user-related state
interface UserState {
  username: string;
  email: string;
}

// Define the initial state for the user slice
const initialState: UserState = {
  username: "",
  email: "",
};

// Create a user slice using createSlice
const userSlice = createSlice({
  name: "user", // Name of the slice, used as the key in the root reducer
  initialState, // Initial state for this slice
  reducers: {
    // Define the setUser reducer function, which updates the user state with the payload data
    setUser: (state, action: PayloadAction<UserState>) => {
      const { username, email } = action.payload;
      state.username = username;
      state.email = email;
    },
  },
});

// Export the setUser action creator for dispatching the setUser action
export const { setUser } = userSlice.actions;

// Export the reducer function generated by createSlice as the default export of this module
export default userSlice.reducer;
